### ISSUE TITLE
May I know the versions of the libraries?

### ISSUE THREAD

**Issue by liujin99** [compl-ai/compl-ai#16]
May I know the specific versions of the libraries used? I encountered a version conflict issue, which prevents the code from running.

**Comment by pavol-bielik** [comment]
Hi @liujin99,

you can find the library versions in [pyproject.toml](https://github.com/compl-ai/compl-ai/blob/main/pyproject.toml).

Let us know if this helps or more details about the conflict such that we can help you resolve it.

**Comment by liujin99** [comment]
Thanks for your reply! The conflict was fixed.
